### ISSUE TITLE
Cert.der is dead?

### ISSUE THREAD

**Issue by clyra** [andybalholm/redwood-config#4]
Hi,

It seems that http://203.0.113.1/cert.der. is dead. Also, may you provide further instructions about how to generate the required .pem files? ty

**Comment by andybalholm** [comment]
That link only works if you are accessing it through a Redwood proxy; it returns the root certificate the proxy is using.

To generate your root certificates, follow steps 1 to 4 at https://www.wikihow.com/Be-Your-Own-Certificate-Authority, except omit the `-des3` parameter from the first command.

**Comment by clyra** [comment]
Hi,

ty!

**Comment by mrbluecoat** [comment]
Some additional recent gotchas and guides:

https://blog.nviso.eu/2018/01/31/using-a-custom-root-ca-with-burp-for-inspecting-android-n-traffic/

https://github.com/FiloSottile/mkcert/issues/174

https://github.com/FiloSottile/mkcert/issues/276

https://ivrodriguez.com/installing-self-signed-certificates-on-android/
