### ISSUE TITLE
Safe browsing enabled for too many requests

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood-config#6]
I like the idea of safe browsing or safe searchs. However it seems this line
https://github.com/andybalholm/redwood-config/blob/6a5ff2ce25d2c83b1e3ff48cdca7ca00b6c20221/safesearch.conf#L1
activates not only for google searches but also for requests to dl.google.com, which prevents Google Chrome repository access.

How can I keep it active on 'google search' but not on dl.google.com?

**Comment by andybalholm** [comment]
Just make it more specific:

    www.google.com safe=vss

Or maybe, to ensure it still works on google.ca etc.:

    /www\.google\./h safe=vss

**Comment by HiranChaudhuri** [comment]
I will give that a try.
Is there a way to exclude dl.google.com?

How does redwood behave if several matches are found in safesearch.com? Would the first match be used or all of them?

**Comment by HiranChaudhuri** [comment]
Ok. having checked
https://github.com/andybalholm/redwood/blob/78bdcf98272509d237f4e4f0ea3f8d7678ec2888/queries.go#L72
it seems to me redwood would process all matching lines, not just the first.

So I cannot write a line with the domain and nothing to have nothing added to the domain, if afterwards another line would still match. I really have to make the matching more specific as you suggest.

**Comment by andybalholm** [comment]
That's right. All matches will be used.

**Comment by HiranChaudhuri** [comment]
Your suggestion worked for me.

Sometimes I wish there would be more features like excludes or somethiing, then at the same time I appreciate the simplicity of the code you created. And I believe simplicity is a benefit both for maintenance as well as for understanding. Thank you so much for sharing that work.
